### PR TITLE
[misc] migrate to the native mongo driver

### PR DESCRIPTION
**Pull request by das7pad**
### Description

For https://github.com/overleaf/issues/issues/2907
This PR is migrating the mongo driver from mongojs to mongodb -- the native driver.

The current revision is a bit unclean as it mixes Promises with callbacks. Refactoring all of contacts for async/await is too much work to code and review at this time.

#### Related Issues / PRs

https://github.com/overleaf/issues/issues/2907
Previous migration: https://github.com/overleaf/chat/pull/53 https://github.com/overleaf/chat/pull/54

### Review

<details>
<summary> changed startup </summary>

The startup behavior has been changed in the chat service already https://github.com/overleaf/chat/pull/54 and is running with success in prod by now.

> This PR changes the startup of the contacts service to not accept any http requests until after the mongo connection has been established. It also adds the correct way to handle connection setup errors, to catch and log them -- vs just letting them bubble up as unhandled PromiseRejections.
> 
> The web service can start without an established/working mongo connection, which is bad. Eventually we can port this snippet over.

</details>

#### Potential Impact

High. All of contacts.

#### Manual Testing Performed

- contacts lookup in the share modal works
- accepting an invite increases the ref-counter for the given contact (`n` field in mongo)

  `dev-environment$ echo 'db.contacts.find()' | bin/mongo`

---

Maybe we should publish `app/js/mongodb.js` as an npm module? cc @jdleesmiller

### CODE REVIEW

**Review by mserranom — APPROVED** [review]
Looks good! I just found `clientConnecting` name a bit confusing, it initially suggests it's a boolean, or that it's expected to control something. Possibly worth keeping it as it is for consistency, since it's copied from other services.

**Comment by das7pad** [comment]
> Looks good! I just found `clientConnecting` name a bit confusing, it initially suggests it's a boolean, or that it's expected to control something. Possibly worth keeping it as it is for consistency, since it's copied from other services.

Thanks for the feedback. Just three services into the migration we can still adjust it. Do you have a better name in mind?

**Comment by das7pad** [comment]
> > Looks good! I just found `clientConnecting` name a bit confusing, it initially suggests it's a boolean, or that it's expected to control something. Possibly worth keeping it as it is for consistency, since it's copied from other services.
> 
> Thanks for the feedback. Just three services into the migration we can still adjust it. Do you have a better name in mind?

Addressed in https://github.com/overleaf/chat/pull/56. Which I amended and force-pushed into this PR.

**Comment by das7pad** [comment]
Another iteration of the db/collection interaction https://github.com/overleaf/chat/pull/57 has been included in this PR -- reducing the size of the diff again.

**Review by mserranom — APPROVED** [review]
👌

**Comment by das7pad** [comment]
I've added a similar commit as https://github.com/overleaf/chat/pull/60 to this PR.

**Review by mserranom — APPROVED** [review]
looks good!

**Pull request merged**
